/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GestorMETA_BD.GestorMETA_BD;
import GestorMETA_BD.META_BDNuevoException;
import GestorMETA_BD.META_BDRecuperadoException;
import GestorMETA_BD.META_BDSobreescritoException;
import GestorMETA_BD.SinTablasException;
import LogicaCommandMETA_BD.CommandMETA_BD;
import LogicaCommandMETA_BD.CreadorMETA_BD;
import LogicaCommandMETA_BD.RecuperadorMETA_BD;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author paul
 */
public class RecuperarDatos extends javax.swing.JFrame {

    private static final File ARCHIVO = new File("archivos/META_BD.csv");
    private final GestorMETA_BD gestorMETA_BD;
    private CommandMETA_BD commandMETA_BD;
    
    /**
     * Creates new form RecuperarDatos
     */
    public RecuperarDatos() {
        initComponents();
        gestorMETA_BD = new GestorMETA_BD();
    }
    
    private void ejecutar() {
        try {
            commandMETA_BD.ejecutar(ARCHIVO);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No existe el archivo META_BD");
        } catch (SinTablasException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (META_BDSobreescritoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (META_BDNuevoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (META_BDRecuperadoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
            try {
                this.dispose();
                showVentanaPrincipal();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "No existe el archivo META_BD");
            }
        }
    }
    
    private void showVentanaPrincipal() throws IOException {
        Principal ventana = new Principal(ARCHIVO);
        ventana.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bNuevos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("¿Desea recuperar los datos anteriores?");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bNuevos.setText("Nuevos");
        bNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bNuevos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bNuevos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        commandMETA_BD = new RecuperadorMETA_BD(gestorMETA_BD);
        ejecutar();
        
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevosActionPerformed
        
        commandMETA_BD = new CreadorMETA_BD(gestorMETA_BD);
        ejecutar();
        
    }//GEN-LAST:event_bNuevosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bNuevos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
